In [1]:
import pandas as pd
from rapidfuzz import process, fuzz
import unidecode
import re

In [2]:
categories = pd.read_parquet(r'../export/small_parquet/municiplity.parquet')
categories

                    DE_MUNICIP
0                       ABRERA
1                      ACEBEDO
2                  ADEJE CASCO
3                      AGUILON
4          ALAMEDA DE LA SAGRA
..                         ...
804      VILLASILA DE VALDAVIA
805  VILLAZANZO DE VALDERADUEY
806            VITORIA-GASTEIZ
807                    VIVEIRO
808                      YAIZA

[809 rows x 1 columns]

In [3]:
categories.nunique()

DE_MUNICIP    809
dtype: int64

In [4]:
categories.dtypes

DE_MUNICIP    object
dtype: object

In [5]:
categories['DE_MUNICIP'] = categories['DE_MUNICIP'].str.strip()

In [6]:
categories.sort_values(by='DE_MUNICIP', inplace=True)
categories.head()

             DE_MUNICIP
201
202           A CORUÃ‘A
203  ABIA DE LAS TORRES
0                ABRERA
1               ACEBEDO

In [7]:
categories.isna().sum()

DE_MUNICIP    0
dtype: int64

In [8]:
categories = categories[categories['DE_MUNICIP'].str.strip() != '']
categories.shape

(808, 1)

In [9]:
latlong_data = pd.read_csv(r"..\BD_MUNICIPIOS-ENTIDADES\MUNICIPIOS.csv",
                           delimiter=';',
                           encoding='latin1')
latlong_data.head()

,COD_INE,ID_REL,COD_GEO,COD_PROV,PROVINCIA,NOMBRE_ACTUAL,POBLACION_MUNI,SUPERFICIE,PERIMETRO,COD_INE_CAPITAL,CAPITAL,POBLACION_CAPITAL,HOJA_MTN25,LONGITUD_ETRS89_REGCAN95,LATITUD_ETRS89_REGCAN95,ORIGENCOOR,ALTITUD,ORIGENALTITUD
0,1001000000,1010014,1010,1,Araba/Álava,Alegría-Dulantzi,2961,"1994,5872",35069,1001000101,Alegría-Dulantzi,2842,0113-3,"-2,512507724","42,84045247",Detección automática,568,MDT
1,1002000000,1010029,1020,1,Araba/Álava,Amurrio,10346,"9617,86",65701,1002000201,Amurrio,9256,0086-4,"-3,001015194","43,05265767",Detección automática,217,MDT
2,1003000000,1010035,1030,1,Araba/Álava,Aramaio,1353,"7308,96",42097,1003000601,Ibarra,731,0087-4,"-2,564829379","43,05257873",Detección automática,325,MDT
3,1004000000,1010040,1040,1,Araba/Álava,Artziniega,1868,"2728,73",22886,1004000101,Artziniega,1732,0086-1,"-3,13052099","43,1217919",Detección automática,199,MDT
4,1006000000,1010066,1060,1,Araba/Álava,Armiñón,233,"1297,27",24707,1006000101,Armiñón,106,0137-4,"-2,872270813","42,72340924",Detección automática,466,MDT

In [10]:
latlong_data = latlong_data[['NOMBRE_ACTUAL', 'PROVINCIA', 'LONGITUD_ETRS89_REGCAN95', 'LATITUD_ETRS89_REGCAN95']]
latlong_data.shape

(8132, 4)

In [11]:
latlong_data.rename(columns={
    'NOMBRE_ACTUAL':'DE_MUNICIP',
    'PROVINCIA':'PROVINCE',
    'LONGITUD_ETRS89_REGCAN95':'LONGITUDE',
    'LATITUD_ETRS89_REGCAN95':'LATITUDE'
},
inplace=True)
latlong_data.head()

         DE_MUNICIP     PROVINCE     LONGITUDE     LATITUDE
0  Alegría-Dulantzi  Araba/Álava  -2,512507724  42,84045247
1           Amurrio  Araba/Álava  -3,001015194  43,05265767
2           Aramaio  Araba/Álava  -2,564829379  43,05257873
3        Artziniega  Araba/Álava   -3,13052099   43,1217919
4           Armiñón  Araba/Álava  -2,872270813  42,72340924

In [12]:
latlong_data.dtypes

DE_MUNICIP    object
PROVINCE      object
LONGITUDE     object
LATITUDE      object
dtype: object

In [13]:
latlong_data['DE_MUNICIP'] = latlong_data['DE_MUNICIP'].str.strip().str.upper()
latlong_data['PROVINCE'] = latlong_data['PROVINCE'].str.strip()
latlong_data['LATITUDE'] = latlong_data['LATITUDE'].str.replace(',', '.').astype('float64')
latlong_data['LONGITUDE'] = latlong_data['LONGITUDE'].str.replace(',', '.').astype('float64')
print(latlong_data.dtypes)
latlong_data.head()

DE_MUNICIP     object
PROVINCE       object
LONGITUDE     float64
LATITUDE      float64
dtype: object

         DE_MUNICIP     PROVINCE  LONGITUDE   LATITUDE
0  ALEGRÍA-DULANTZI  Araba/Álava  -2.512508  42.840452
1           AMURRIO  Araba/Álava  -3.001015  43.052658
2           ARAMAIO  Araba/Álava  -2.564829  43.052579
3        ARTZINIEGA  Araba/Álava  -3.130521  43.121792
4           ARMIÑÓN  Araba/Álava  -2.872271  42.723409

In [14]:
latlong_data.sort_values(by='DE_MUNICIP', inplace=True)
latlong_data.head()

     DE_MUNICIP    PROVINCE  LONGITUDE   LATITUDE
4891   A ARNOIA     Ourense  -8.135751  42.253066
2132     A BAÑA    A Coruña  -8.758003  42.961898
4902     A BOLA     Ourense  -7.928518  42.140937
2143   A CAPELA    A Coruña  -8.068806  43.435552
5292   A CAÑIZA  Pontevedra  -8.273359  42.212754

In [15]:
merged = categories.merge(latlong_data, on=['DE_MUNICIP'], how='left')
merged

                  DE_MUNICIP   PROVINCE  LONGITUDE   LATITUDE
0                  A CORUÃ‘A        NaN        NaN        NaN
1         ABIA DE LAS TORRES   Palencia  -4.421902  42.420220
2                     ABRERA  Barcelona   1.901569  41.516398
3                    ACEBEDO       León  -5.115871  43.040732
4                   ACEUCHAL    Badajoz  -6.487251  38.647755
..                       ...        ...        ...        ...
809                 YUNQUERA     Málaga  -4.917332  36.734203
810                    ZAFRA    Badajoz  -6.418559  38.426344
811                 ZARAGOZA   Zaragoza  -0.877318  41.656208
812  ZARZOSA DE RIO PISUERGA        NaN        NaN        NaN
813                    ZUERA   Zaragoza  -0.787165  41.868393

[814 rows x 4 columns]

In [16]:
merged[merged['LONGITUDE'].isna()]

                  DE_MUNICIP PROVINCE  LONGITUDE  LATITUDE
0                  A CORUÃ‘A      NaN        NaN       NaN
6                ADEJE CASCO      NaN        NaN       NaN
10                   AGUILON      NaN        NaN       NaN
11                   AGUIMES      NaN        NaN       NaN
12                  AGÃœIMES      NaN        NaN       NaN
..                       ...      ...        ...       ...
798                VILLAYUSO      NaN        NaN       NaN
800           VILOBI D'ONYAR      NaN        NaN       NaN
801                  VINAROS      NaN        NaN       NaN
805       XUNQUEIRA DE AMBIA      NaN        NaN       NaN
812  ZARZOSA DE RIO PISUERGA      NaN        NaN       NaN

[275 rows x 4 columns]

In [17]:
merged[merged['DE_MUNICIP'].duplicated(keep=False)]

      DE_MUNICIP            PROVINCE  LONGITUDE   LATITUDE
131      CABANES  Castelló/Castellón   0.045412  40.156104
132      CABANES              Girona   2.977957  42.307504
199        CIEZA              Murcia  -1.427730  38.236594
200        CIEZA           Cantabria  -4.096722  43.221056
433       MIERES              Girona   2.640292  42.123296
434       MIERES            Asturias  -5.772657  43.248794
579         SADA             Navarra  -1.397668  42.585825
580         SADA            A Coruña  -8.253590  43.351531
718      TORRENT   València/Valencia  -0.465982  39.436721
719      TORRENT              Girona   3.128197  41.951843
771  VILLAESCUSA              Zamora  -5.464099  41.206136
772  VILLAESCUSA           Cantabria  -3.856639  43.370333

In [18]:
categories_prov = pd.read_parquet(r'..\export\small_parquet\muncipility_province.parquet')
print(categories_prov.shape)
categories_prov.head()

(778, 2)

  Municipality Province
0         Abla  Almería
1     Abrucena  Almería
2       Adamuz  Córdoba
3         Adra  Almería
4        Agrón  Granada

In [19]:
same_name_diff_prov = merged[merged['DE_MUNICIP'].duplicated()]['DE_MUNICIP'].values
same_name_diff_prov

array(['CABANES', 'CIEZA', 'MIERES', 'SADA', 'TORRENT', 'VILLAESCUSA'],
      dtype=object)

In [20]:
categories_prov[categories_prov['Municipality'].isin(same_name_diff_prov)]

Empty DataFrame
Columns: [Municipality, Province]
Index: []

In [21]:
def clean_municipality(name):
    if not isinstance(name, str): return ""
    # 1. Fix specific encoding artifacts
    name = name.replace("Ã‘", "Ñ").replace("Ã“", "Ó")
    
    # 2. Expand common abbreviations
    name = name.replace("S/C", "SANTA CRUZ")
    name = name.replace("S.", "SAN")
    
    # 3. Fix trailing articles e.g., "CUERVO (EL)" -> "EL CUERVO"
    name = re.sub(r'^(.*?)\s*\((EL|LA|LOS|LAS)\)$', r'\2 \1', name)
    
    # 4. Remove accents and convert to uppercase for baseline comparison
    name = unidecode.unidecode(name).upper()
    return name.strip()

# Apply cleaning to both lists
clean_dataset = [clean_municipality(name) for name in categories.DE_MUNICIP.tolist()]
clean_all = [clean_municipality(name) for name in latlong_data['DE_MUNICIP'].tolist()]

matches = {}
for original_name, clean_name in zip(categories.DE_MUNICIP.tolist(), clean_dataset):
    
    # Handle bilingual names by splitting at '/'
    parts = clean_name.split('/')
    best_match = None
    best_score = 0
    
    for part in parts:
        result = process.extractOne(
            part,
            clean_all,
            scorer=fuzz.token_sort_ratio,
            score_cutoff=85  # Raised significantly to prevent false positives
        )
        if result and result[1] > best_score:
            best_match = result
            best_score = result[1]
            
    if best_match:
        # Retrieve the original uncleaned name from the target dataframe using the index
        target_original_name = latlong_data['DE_MUNICIP'].iloc[best_match[2]]
        matches[original_name] = target_original_name
    else:
        matches[original_name] = None

In [22]:
matches

{'A CORUÃ‘A': 'A CORUÑA',
 'ABIA DE LAS TORRES': 'ABIA DE LAS TORRES',
 'ABRERA': 'ABRERA',
 'ACEBEDO': 'ACEBEDO',
 'ACEUCHAL': 'ACEUCHAL',
 'ADEJE': 'ADEJE',
 'ADEJE CASCO': None,
 'ADEMUZ': 'ADEMUZ',
 'AGRAMUNT': 'AGRAMUNT',
 'AGUADULCE': 'AGUADULCE',
 'AGUILON': 'AGUILÓN',
 'AGUIMES': 'AGÜIMES',
 'AGÃœIMES': None,
 'AITONA': 'AITONA',
 'AJO': None,
 'ALAMEDA DE LA SAGRA': 'ALAMEDA DE LA SAGRA',
 'ALARO': 'ALARÓ',
 'ALBACETE': 'ALBACETE',
 'ALBENDIEGO': 'ALBENDIEGO',
 'ALBOCASSER': 'ALBOCÀSSER',
 'ALBOLOTE': 'ALBOLOTE',
 'ALBURQUERQUE': 'ALBURQUERQUE',
 'ALCALA DE HENARES': 'ALCALÁ DE HENARES',
 'ALCALA DE XIVERT': 'ALCALÀ DE XIVERT',
 'ALCALA LA REAL': 'ALCALÁ LA REAL',
 'ALCANAR': 'ALCANAR',
 'ALCAUDETE': 'ALCAUDETE',
 'ALCAZAR DE SAN JUAN': 'ALCÁZAR DE SAN JUAN',
 'ALCAÃ‘IZ': 'ALCAÑIZ',
 'ALCOBENDAS': 'ALCOBENDAS',
 'ALCORCON': 'ALCORCÓN',
 'ALCUBIERRE': 'ALCUBIERRE',
 'ALCUDIA': 'ALCÚDIA',
 'ALDEASECA DE ALBA': 'ALDEASECA DE ALBA',
 'ALDEATEJADA': 'ALDEATEJADA',
 'ALFORJA': 'ALFORJA',
 'ALFOZ DE BRICIA': 'ALFOZ DE BRICIA',
 'ALFOZ DE SANTA GADEA': 'ALFOZ DE SANTA GADEA',
 'ALGARROBO': 'ALGARROBO',
 'ALGECIRAS': 'ALGECIRAS',
 'ALHAURIN DE LA TORRE': 'ALHAURÍN DE LA TORRE',
 'ALICANTE/ALACANT': None,
 'ALJARAQUE': 'ALJARAQUE',
 'ALLARIZ': 'ALLARIZ',
 'ALLER': 'ALLER',
 'ALMANSA': 'ALMANSA',
 'ALMAZORA': None,
 'ALMENARA': 'ALMENARA',
 'ALMENDRALEJO': 'ALMENDRALEJO',
 'ALMERIA': 'ALMERÍA',
 'ALMONACID DE LA SIERRA': 'ALMONACID DE LA SIERRA',
 'ALQUERIAS DEL NIÃ‘O PERDIDO': None,
 'AMER': 'AMER',
 'ANDORRA': 'ANDORRA',
 'ANDRATX': 'ANDRATX',
 'ANOETA': 'ANOETA',
 'ANTEQUERA': 'ANTEQUERA',
 'ANTIGUA': 'ANTIGUA',
 'ARAHAL': 'ARAHAL',
 'ARANJUEZ': 'ARANJUEZ',
 'ARENILLAS DE RIOPISUERGA': 'ARENILLAS DE RIOPISUERGA',
 'ARENYS DE MAR': 'ARENYS DE MAR',
 'ARENYS DE MUNT': 'ARENYS DE MUNT',
 'ARGAMASILLA DE ALBA': 'ARGAMASILLA DE ALBA',
 'ARGANDA': 'ARGANZA',
 'ARGANDA DEL REY': 'ARGANDA DEL REY',
 'ARGENTONA': 'ARGENTONA',
 'ARICO': 'ARICO',
 'ARIJA': 'ARIJA',
 'ARMILLA': 'ARMILLA',
 'ARNUERO': 'ARNUERO',
 'ARONA': 'ARONA',
 'ARRECIFE': 'ARRECIFE',
 'ARREDONDO': 'ARREDONDO',
 'ARRONIZ': 'ARRÓNIZ',
 'ARTA': 'ARTÀ',
 'ARTEIXO': 'ARTEIXO',
 'ARUCAS': 'ARUCAS',
 'ASTORGA': 'ASTORGA',
 'AVILA': 'ÁVILA',
 'AYORA': 'AYORA',
 'AÃ‘OVER DE TAJO': 'AÑOVER DE TAJO',
 'BADAJOZ': 'BADAJOZ',
 'BADALONA': 'BADALONA',
 'BADIA DEL VALLES': 'BADIA DEL VALLÈS',
 'BAEZA': 'BAEZA',
 'BAIDES': 'BAIDES',
 'BAILEN': 'BAILÉN',
 'BANYALBUFAR': 'BANYALBUFAR',
 'BARAKALDO': 'BARAKALDO',
 'BARBADAS': 'BARBADÁS',
 'BARCELONA': 'BARCELONA',
 'BAREYO': 'BAREYO',
 'BARRAX': 'BARRAX',
 'BARRIO DE BRICIA': None,
 'BASCONES DE OJEDA': 'BÁSCONES DE OJEDA',
 'BEARIZ': 'BEARIZ',
 'BEAS': 'BEAS',
 'BEAS DE SEGURA': 'BEAS DE SEGURA',
 'BELORADO': 'BELORADO',
 'BENALMADENA': 'BENALMÁDENA',
 'BENALUA': 'BENALÚA',
 'BENASAU': 'BENASAU',
 'BENIARRES': 'BENIARRÉS',
 'BENICARLO': 'BENICARLÓ',
 'BENICASIM': None,
 'BENIDORM': 'BENIDORM',
 'BENILLOBA': 'BENILLOBA',
 'BENQUERENCIA DE LA SERENA': 'BENQUERENCIA DE LA SERENA',
 'BERCIANOS DEL REAL CAMINO': 'BERCIANOS DEL REAL CAMINO',
 'BERGA': 'BERGA',
 'BERGONDO': 'BERGONDO',
 'BERIAIN': 'BERIÁIN',
 'BETXI': 'BETXÍ',
 'BILBAO': 'BILBAO',
 'BOAL': 'BOAL',
 'BORMUJOS': 'BORMUJOS',
 'BOROX': 'BOROX',
 'BORRIANA/BURRIANA': None,
 'BREÃ‘A ALTA': 'BREÑA ALTA',
 'BREÃ‘A BAJA': 'BREÑA BAJA',
 'BROTO': 'BROTO',
 'BUBION': 'BUBIÓN',
 'BUENAVISTA DE VALDAVIA': 'BUENAVISTA DE VALDAVIA',
 'BUENAVISTA DEL NORTE': 'BUENAVISTA DEL NORTE',
 'BURGOS': 'BURGOS',
 'BURON': 'BURÓN',
 'BURRIANA': None,
 'BUSTARES': 'BUSTARES',
 'BUSTILLO DE LA VEGA': 'BUSTILLO DE LA VEGA',
 'CABANAQUINTA/CABAÃ‘AQUINTA': None,
 'CABANES': 'CABANES',
 'CABEZAS DE SAN JUAN (LAS)': 'LAS CABEZAS DE SAN JUAN',
 'CABEZON DE LA SAL': 'CABEZÓN DE LA SAL',
 'CABEZON DE LIEBANA': 'CABEZÓN DE LIÉBANA',
 'CABRERA D?ANOIA': "CABRERA D'ANOIA",
 'CABRERA DÂ´ANOIA': "CABRERA D'ANOIA",
 'CACERES': 'CÁCERES',
 'CALACEITE': 'CALACEITE',
 'CALAFELL': 'CALAFELL',
 'CALAHORRA DE BOEDO': 'CALAHORRA DE BOEDO',
 'CALAMONTE': 'CALAMONTE',
 'CALANDA': 'CALANDA',
 'CALATAYUD': 'CALATAYUD',
 'CALAÃ‘AS': 'CALAÑAS',
 "CALDES D'ESTRAC": "CALDES D'ESTRAC",
 'CALLDETENES': 'CALLDETENES',
 'CALVIA': 'CALVIÀ',
 'CALZADA DE LOS MOLINOS': 'CALZADA DE LOS MOLINOS',
 'CALZADA DE VALDUNCIEL': 'CALZADA DE VALDUNCIEL',
 'CAMARGO': 'CAMARGO',
 'CAMARMA DE ESTERUELAS': 'CAMARMA DE ESTERUELAS',
 'CAMBRE': 'CAMBRE',
 'CAMBRILS': 'CAMBRILS',
 'CAMPO DE CRIPTANA': 'CAMPO DE CRIPTANA',
 'CAMPO REAL': 'CAMPO REAL',
 'CAMPOO DE ENMEDIO': 'CAMPOO DE ENMEDIO',
 'CANDELARIA': 'CANDELARIA',
 'CAPDEPERA': 'CAPDEPERA',
 'CAPILEIRA': 'CAPILEIRA',
 'CARBALLO': 'CARBALLO',
 'CARBONERAS': 'CARBONERAS',
 'CARMONA': 'CARMONA',
 'CARRANQUE': 'CARRANQUE',
 'CARRION DE LOS CONDES': 'CARRIÓN DE LOS CONDES',
 'CARTAGENA': 'CARTAGENA',
 'CARTAMA': 'CÁRTAMA',
 'CARTAYA': 'CARTAYA',
 'CARTES': 'CARTES',
 'CASAS ALTAS': 'CASAS ALTAS',
 'CASAS BAJAS': 'CASAS BAJAS',
 'CASTAÃ‘EDA': 'CASTAÑEDA',
 'CASTELLANOS DE MORISCOS': 'CASTELLANOS DE MORISCOS',
 'CASTELLANOS DE VILLIQUERA': 'CASTELLANOS DE VILLIQUERA',
 'CASTELLDEFELS': 'CASTELLDEFELS',
 'CASTELLOLI': 'CASTELLOLÍ',
 'CASTELLON': 'CASTELLÓ',
 'CASTELLON DE LA PLANA': None,
 'CASTELLON LA PLANA/CASTELLO PL': 'CASTELLOLÍ',
 'CASTILBLANCO DE LOS ARROYOS': 'CASTILBLANCO DE LOS ARROYOS',
 'CASTRILLO DE RIOPISUERGA': 'CASTRILLO DE RIOPISUERGA',
 'CASTRILLO DE VILLAVEGA': 'CASTRILLO DE VILLAVEGA',
 'CASTROJERIZ': 'CASTROJERIZ',
 'CAZORLA': 'CAZORLA',
 'CAÃ‘AMERO': 'CAÑAMERO',
 'CAÃ‘IZAL': 'CAÑIZAL',
 'CEA': 'CEA',
 'CENDEJAS DE ENMEDIO': 'CENDEJAS DE ENMEDIO',
 'CENDEJAS DE LA TORRE': 'CENDEJAS DE LA TORRE',
 'CENIZATE': 'CENIZATE',
 'CERVELLO': 'CERVELLÓ',
 'CESPEDOSA DE TORMES': 'CESPEDOSA DE TORMES',
 'CHICLANA DE LA FRONTERA': 'CHICLANA DE LA FRONTERA',
 'CHILCHES': 'CHILOECHES',
 'CHILCHES/XILXES': 'CHILOECHES',
 'CHINCHILLA DE MONTE-ARAGON': 'CHINCHILLA DE MONTE-ARAGÓN',
 'CHINCHON': 'CHINCHÓN',
 'CHOZAS DE ABAJO': 'CHOZAS DE ABAJO',
 'CIEZA': 'CIEZA',
 'CIHUELA': 'CIHUELA',
 'CILLORIGO DE LIEBANA': 'CILLORIGO DE LIÉBANA',
 'CIUDAD REAL': 'CIUDAD REAL',
 'CIUDAD RODRIGO': 'CIUDAD RODRIGO',
 'CIUTADELLA DE MENORCA': 'CIUTADELLA DE MENORCA',
 'COLLAZOS DE BOEDO': 'COLLAZOS DE BOEDO',
 'COLMENAR DE OREJA': 'COLMENAR DE OREJA',
 'CONDEMIOS DE ABAJO': 'CONDEMIOS DE ABAJO',
 'CONIL DE LA FRONTERA': 'CONIL DE LA FRONTERA',
 'CONSELL': 'CONSELL',
 'CORBERA DE LLOBREGAT': 'CORBERA DE LLOBREGAT',
 'CORDOBA': 'CÓRDOBA',
 'CORIA DEL RIO': 'CORIA DEL RÍO',
 'CORVERA DE TORANZO': 'CORVERA DE TORANZO',
 'COSLADA': 'COSLADA',
 'CRETAS': 'CRETAS',
 'CUADROS': 'CUADROS',
 'CUARTE DE HUERVA': 'CUARTE DE HUERVA',
 'CUBILLAS DE RUEDA': 'CUBILLAS DE RUEDA',
 'CUERVO (EL)': 'EL CUERVO',
 'CULLEREDO': 'CULLEREDO',
 'DAGANZO DE ARRIBA': 'DAGANZO DE ARRIBA',
 'DAIMIEL': 'DAIMIEL',
 'DALIAS': 'DALÍAS',
 'DENIA': 'DÉNIA',
 'DESTRIANA': 'DESTRIANA',
 'DONOSTIA-SAN SEBASTIAN': 'DONOSTIA/SAN SEBASTIÁN',
 'DOS HERMANAS': 'DOS HERMANAS',
 'ECIJA': 'ÉCIJA',
 'EIVISSA': 'EIVISSA',
 'EJEA': None,
 'EL CUBILLO DE UCEDA': 'EL CUBILLO DE UCEDA',
 'EL CUERVO DE SEVILLA': 'EL CUERVO DE SEVILLA',
 'EL ESPINAR': 'EL ESPINAR',
 'EL GOLFO': None,
 'EL PINAR': 'EL PINAR',
 'EL PINAR DE EL HIERRO': 'EL PINAR DE EL HIERRO',
 'EL PRAT DE LLOBREGAT': 'EL PRAT DE LLOBREGAT',
 'EL PUERTO DE SANTA MARIA': 'EL PUERTO DE SANTA MARÍA',
 'EL ROSARIO': 'EL ROSARIO',
 'EL TANQUE': 'EL TANQUE',
 'EL VENDRELL': 'EL VENDRELL',
 'EL VERGER': 'EL VERGER',
 'ELCHE': None,
 'ELCHE/ELX': None,
 'ELEXALDE': None,
 'ELS HOSTALETS DE PIEROLA': 'ELS HOSTALETS DE PIEROLA',
 'ELS POBLETS': 'ELS POBLETS',
 'ENCINILLAS': 'ENCINILLAS',
 'ENTRAMBASAGUAS': 'ENTRAMBASAGUAS',
 'ES MERCADAL': 'ES MERCADAL',
 'ESCALANTE': 'ESCALANTE',
 'ESPARTINAS': 'ESPARTINAS',
 'ESPINO DE LA ORBADA': 'ESPINO DE LA ORBADA',
 'ESPINOSA DE VILLAGONZALO': 'ESPINOSA DE VILLAGONZALO',
 'ESPLUGUES DE LLOBREGAT': 'ESPLUGUES DE LLOBREGAT',
 'ESPORLES': 'ESPORLES',
 'ESQUIVIAS': 'ESQUIVIAS',
 'ESTEPA': 'ESTEPA',
 'ESTEPONA': 'ESTEPONA',
 'ESTREMERA': 'ESTREMERA',
 'FELANITX': 'FELANITX',
 'FIGUERES': 'FIGUERES',
 'FISTERRA': 'FISTERRA',
 'FOGARS DE LA SELVA': 'FOGARS DE LA SELVA',
 'FONELAS': 'FONELAS',
 'FORMENTERA': 'FORMENTERA',
 'FOZ': 'FOZ',
 'FRONTERA': 'FRONTERA',
 'FUENGIROLA': 'FUENGIROLA',
 'FUENTE EL FRESNO': 'FUENTE EL FRESNO',
 'FUENTE TOJAR': 'FUENTE-TÓJAR',
 'FUENTE VAQUEROS': 'FUENTE VAQUEROS',
 'FUENTE-OBEJUNA': 'FUENTE OBEJUNA',
 'FUENTES DE BEJAR': 'FUENTES DE BÉJAR',
 'FUSTIÃ‘ANA': 'FUSTIÑANA',
 'GALAPAGOS': 'GALÁPAGOS',
 'GALDAR': 'GÁLDAR',
 'GALVE DE SORBE': 'GALVE DE SORBE',
 'GANDIA': 'GANDIA',
 'GARCIA': 'GARCIA',
 'GARLITOS': 'GARLITOS',
 'GARROBO (EL)': 'EL GARROBO',
 'GARRUCHA': 'GARRUCHA',
 'GIBRALEON': 'GIBRALEÓN',
 'GINESTAR': 'GINESTAR',
 'GIRONA': 'GIRONA',
 'GOMECELLO': 'GOMECELLO',
 'GRADEFES': 'GRADEFES',
 'GRANADA': 'GRANADA',
 'GRANADILLA DE ABONA': 'GRANADILLA DE ABONA',
 'GRIJALBA': 'GRIJALBA',
 'GUADALAJARA': 'GUADALAJARA',
 'GUADALUPE': 'GUADALUPE',
 'GUADIX': 'GUADIX',
 'GUARDAMAR DEL SEGURA': 'GUARDAMAR DEL SEGURA',
 'GUIA DE ISORA': 'GUÍA DE ISORA',
 'GUIJUELO': 'GUIJUELO',
 'GUILLENA': 'GUILLENA',
 'GUISSONA': 'GUISSONA',
 'HARO': 'HARO',
 'HERMIGUA': 'HERMIGUA',
 'HERNIALDE': 'HERNIALDE',
 'HERRERA': 'HERRERA',
 'HERRERA DE PISUERGA': 'HERRERA DE PISUERGA',
 'HERRERIAS': 'HERRERÍAS',
 'HIENDELAENCINA': 'HIENDELAENCINA',
 'HITA': 'HITA',
 'HORCAJO MEDIANERO': 'HORCAJO MEDIANERO',
 'HORNILLOS DEL CAMINO': 'HORNILLOS DEL CAMINO',
 'HOSPITAL DE ORBIGO': 'HOSPITAL DE ÓRBIGO',
 'HUELVA': 'HUELVA',
 'HUERMECES DEL CERRO': 'HUÉRMECES DEL CERRO',
 'HUESCA': 'HUESCA',
 'HUETOR TAJAR': 'HUÉTOR TÁJAR',
 'IBARRA': 'IBARRA',
 'ICOD DE LOS VINOS': 'ICOD DE LOS VINOS',
 'IGUALADA': 'IGUALADA',
 'ILLESCAS': 'ILLESCAS',
 'ILLORA': 'ÍLLORA',
 'INCA': 'INCA',
 'ITERO DEL CASTILLO': 'ITERO DEL CASTILLO',
 'IZNAJAR': 'IZNÁJAR',
 'IZNATE': 'IZNATE',
 'IZNATORAF': 'IZNATORAF',
 'JADRAQUE': 'JADRAQUE',
 'JAEN': 'JAÉN',
 'JAVEA': None,
 'JAVEA/XABIA': None,
 'JEREZ DE LA FRONTERA': 'JEREZ DE LA FRONTERA',
 'JIRUEQUE': 'JIRUEQUE',
 'JORBA': 'JORBA',
 "L'ALFAS DEL PI": "L'ALFÀS DEL PI",
 "L'HOSPITALET DE LLOBREGAT": "L'HOSPITALET DE LLOBREGAT",
 'L?ESCALA': "L'ESCALA",
 'LA ALMUNIA': None,
 'LA BAÃ‘EZA': 'LA BAÑEZA',
 'LA CABEZA DE BEJAR': 'LA CABEZA DE BÉJAR',
 'LA CODOSERA': 'LA CODOSERA',
 'LA CONCHA': None,
 'LA GINETA': 'LA GINETA',
 "LA GRANJA D'ESCARP": "LA GRANJA D'ESCARP",
 'LA GUANCHA': 'LA GUANCHA',
 'LA HUERCE': 'LA HUERCE',
 'LA IGLESIA': None,
 'LA LASTRILLA': 'LA LASTRILLA',
 'LA LLOSA': 'LA LLOSA',
 'LA MUELA': 'LA MUELA',
 'LA PALMA DEL CONDADO': 'LA PALMA DEL CONDADO',
 'LA POLA': None,
 'LA POLA DE GORDON': 'LA POLA DE GORDÓN',
 'LA SERNA': 'LA SERNA',
 'LA TAHA': 'LA TAHA',
 'LA TALA': 'LA TALA',
 'LA TOBA': 'LA TOBA',
 "LA TORRE D'EN DOMENEC": "LA TORRE D'EN DOMÉNEC",
 'LA UNION': 'LA UNIÓN',
 "LA VALL D'UIXO": "LA VALL D'UIXÓ",
 'LA VECILLA': 'LA VECILLA',
 'LA VELLES': 'LA VELLÉS',
 'LAGUNA DE NEGRILLOS': 'LAGUNA DE NEGRILLOS',
 'LAMASON': 'LAMASÓN',
 'LANTADILLA': 'LANTADILLA',
 'LAREDO': 'LAREDO',
 'LAS PALMAS DE G.C.': None,
 'LAS PALMAS DE GRAN CANARIA': 'LAS PALMAS DE GRAN CANARIA',
 'LAS ROZAS DE MADRID': 'LAS ROZAS DE MADRID',
 'LASARTE-ORIA': 'LASARTE-ORIA',
 'LEBRIJA': 'LEBRIJA',
 'LEGANES': 'LEGANÉS',
 'LEIOA': 'LEIOA',
 'LEITZA': 'LEITZA',
 'LENA': 'LENA',
 'LEON': 'LEÓN',
 'LEPE': 'LEPE',
 'LES MASIES DE VOLTREGA': 'LES MASIES DE VOLTREGÀ',
 "LES PLANES D'HOSTOLES": "LES PLANES D'HOSTOLES",
 'LIERGANES': 'LIÉRGANES',
 'LINARES': 'LINARES',
 'LLANSA': None,
 'LLEIDA': 'LLEIDA',
 'LLORET DE MAR': 'LLORET DE MAR',
 'LLUCMAJOR': 'LLUCMAJOR',
 'LOECHES': 'LOECHES',
 'LOGROÃ‘O': 'LOGROÑO',
 'LOJA': 'LOJA',
 'LOMA DE UCIEZA': 'LOMA DE UCIEZA',
 'LORCA': 'LORCA',
 'LOS CORRALES': 'LOS CORRALES',
 'LOS CORRALES DE BUELNA': 'LOS CORRALES DE BUELNA',
 'LOS REALEJOS': 'LOS REALEJOS',
 'LOS SANTOS': 'LOS SANTOS',
 'LOS SILOS': 'LOS SILOS',
 'LUCENA': 'LUCENA',
 'LUENA': 'LUENA',
 'LUESIA': 'LUESIA',
 'LUESMA': 'LUESMA',
 'LUGO': 'LUGO',
 'LÂ´ESCALA': "L'ESCALA",
 'MADRID': 'MADRID',
 'MAELLA': 'MAELLA',
 'MAHORA': 'MAHORA',
 'MAIRENA DEL ALCOR': 'MAIRENA DEL ALCOR',
 'MAIRENA DEL ALJARAFE': 'MAIRENA DEL ALJARAFE',
 'MALAGA': 'MÁLAGA',
 'MALGRAT DE MAR': 'MALGRAT DE MAR',
 'MANACOR': 'MANACOR',
 'MANCHA REAL': 'MANCHA REAL',
 'MANLLEU': 'MANLLEU',
 'MANRESA': 'MANRESA',
 'MANSILLA MAYOR': 'MANSILLA MAYOR',
 'MARAÃ‘A': 'MARAÑA',
 'MARBELLA': 'MARBELLA',
 'MARCILLA DE CAMPOS': 'MARCILLA DE CAMPOS',
 'MARIA DE HUERVA': 'MARÍA DE HUERVA',
 'MARINA DE CUDEYO': 'MARINA DE CUDEYO',
 'MARRATXI': 'MARRATXÍ',
 'MARTOS': 'MARTOS',
 'MARUGAN': 'MARUGÁN',
 'MASIDE': 'MASIDE',
 'MATAMOROSA': None,
 'MATARO': 'MATARÓ',
 'MAZALEON': 'MAZALEÓN',
 'MAÃ“': 'MAÓ',
 'MEDIO CUDEYO': 'MEDIO CUDEYO',
 'MEDRANDA': 'MEDRANDA',
 'MEJORADA DEL CAMPO': 'MEJORADA DEL CAMPO',
 'MELGAR DE FERNAMENTAL': 'MELGAR DE FERNAMENTAL',
 'MENGIBAR': 'MENGÍBAR',
 'MERUELO': 'MERUELO',
 'MIENGO': 'MIENGO',
 'MIERA': 'MIERA',
 'MIERES': 'MIERES',
 'MIERES DEL CAMIN': None,
 'MIGUEL ESTEBAN': 'MIGUEL ESTEBAN',
 'MIGUELTURRA': 'MIGUELTURRA',
 'MIJAS': 'MIJAS',
 'MIRALRIO': 'MIRALRÍO',
 'MIRAVET': 'MIRAVET',
 'MIÃ‘O': 'MIÑO',
 'MOCLIN': 'MOCLÍN',
 'MOGAN': 'MOGÁN',
 'MOGUER': 'MOGUER',
 'MOLINS DE REI': 'MOLINS DE REI',
 'MOLLERUSSA': 'MOLLERUSSA',
 'MOLLET DEL VALLES': 'MOLLET DEL VALLÈS',
 'MONACHIL': 'MONACHIL',
 'MONCOFA': 'MONCOFA',
 'MONDA': 'MONDA',
 'MONFERO': 'MONFERO',
 'MONT-ROIG DEL CAMP': 'MONT-ROIG DEL CAMP',
 'MONTEJO': 'MONTEJO',
 'MONTELLANO': 'MONTELLANO',
 'MONTERRUBIO DE ARMUÃ‘A': 'MONTERRUBIO DE ARMUÑA',
 'MONTGAT': 'MONTGAT',
 'MONTIJO': 'MONTIJO',
 'MONTMANEU': 'MONTMANEU',
 "MORA D'EBRE": "MÓRA D'EBRE",
 'MORISCOS': 'MORISCOS',
 'MORON DE LA FRONTERA': 'MORÓN DE LA FRONTERA',
 'MORON FRONTERA': None,
 'MOSTOLES': 'MÓSTOLES',
 'MOTRIL': 'MOTRIL',
 'MURCHANTE': 'MURCHANTE',
 'MURCIA': 'MURCIA',
 'MURIEDAS': None,
 'MURO': 'MURO',
 'MURO DE ALCOY': 'MURO DE ALCOY',
 'MURO DEL ALCOY': 'MURO DE ALCOY',
 'NAVALVILLAR DE IBOR': 'NAVALVILLAR DE IBOR',
 'NAVIA': 'NAVIA',
 'NIJAR': 'NÍJAR',
 'NOGAL DE LAS HUERTAS': 'NOGAL DE LAS HUERTAS',
 'NUMANCIA DE LA SAGRA': 'NUMANCIA DE LA SAGRA',
 'O CARBALLIÃ‘O': 'O CARBALLIÑO',
 'ODENA': 'ÒDENA',
 'OLEIROS': 'OLEIROS',
 'OLIVA': 'OLIVA',
 'ONDA': 'ONDA',
 'ONDARROA': 'ONDARROA',
 'ORERA': 'ORERA',
 'OSORNILLO': 'OSORNILLO',
 'OSORNO': None,
 'OSORNO LA MAYOR': 'OSORNO LA MAYOR',
 'OURENSE': 'OURENSE',
 'PACS DEL PENEDES': 'PACS DEL PENEDÈS',
 'PAJARA': 'PÁJARA',
 'PALAFOLLS': 'PALAFOLLS',
 'PALAFRUGELL': 'PALAFRUGELL',
 'PALENCIA': 'PALENCIA',
 'PALENCIA DE NEGRILLA': 'NEGRILLA DE PALENCIA',
 'PALMA': 'PALMA',
 'PALMA DE MALLORCA': None,
 'PALMA DEL CONDADO (LA)': 'LA PALMA DEL CONDADO',
 'PALMACES DE JADRAQUE': 'PÁLMACES DE JADRAQUE',
 'PAMPLONA': None,
 'PAMPLONA/IRUÃ‘A': 'IRUN',
 'PARACUELLOS DE JARAMA': 'PARACUELLOS DE JARAMA',
 'PARAMO DE BOEDO': 'PÁRAMO DE BOEDO',
 'PECHINA': 'PECHINA',
 'PEDRERA': 'PEDRERA',
 'PEDRO MUÃ‘OZ': 'PEDRO MUÑOZ',
 'PEDROSA DE LA VEGA': 'PEDROSA DE LA VEGA',
 'PEDROSA DEL PARAMO': 'PEDROSA DEL PÁRAMO',
 'PENAGOS': 'PENAGOS',
 'PESAGUERO': 'PESAGUERO',
 'PESQUERA': 'PESQUERA',
 'PEÃ‘ARROYA-PUEBLONUEVO': 'PEÑARROYA-PUEBLONUEVO',
 'PEÃ‘ARRUBIA': 'PEÑARRUBIA',
 'PEÃ‘ISCOLA': None,
 'PIELAGOS': 'PIÉLAGOS',
 'PIERA': 'PIERA',
 'PILES': 'PILES',
 'PILOÃ‘A': 'PILOÑA',
 'PINA DE EBRO': 'PINA DE EBRO',
 'PIZARRAL': 'PIZARRAL',
 'PLASENCIA': 'PLASENCIA',
 'POBLADURA DEL VALLE': 'POBLADURA DEL VALLE',
 'POIO': 'POIO',
 'POLACIONES': 'POLACIONES',
 'POLANCO': 'POLANCO',
 'POLLENÃ‡A': None,
 'POMALUENGO': None,
 'PONTEVEDRA': 'PONTEVEDRA',
 'PORTUGALETE': 'PORTUGALETE',
 'PORTUGOS': 'PÓRTUGOS',
 'POSADA DE VALDEON': 'POSADA DE VALDEÓN',
 'POZO CAÃ‘ADA': 'POZO CAÑADA',
 'POZUELO DE ALARCON': 'POZUELO DE ALARCÓN',
 'PRIEGO DE CORDOBA': 'PRIEGO DE CÓRDOBA',
 'PUEBLA DE GUZMAN': 'PUEBLA DE GUZMÁN',
 'PUENTE DEL CONGOSTO': 'PUENTE DEL CONGOSTO',
 'PUENTE VIESGO': 'PUENTE VIESGO',
 'PUENTENANSA': None,
 'PUERTO DE LA CRUZ': 'PUERTO DE LA CRUZ',
 'PUERTO DE SANTA MARIA (EL)': 'EL PUERTO DE SANTA MARÍA',
 'PUERTO DEL ROSARIO': 'PUERTO DEL ROSARIO',
 'PUNTA UMBRIA': 'PUNTA UMBRÍA',
 'PURULLENA': 'PURULLENA',
 'QUART DE POBLET': 'QUART DE POBLET',
 'RAMALES DE LA VICTORIA': 'RAMALES DE LA VICTORIA',
 'REINOSA': 'REINOSA',
 'RENEDO': None,
 'RENEDO DE LA VEGA': 'RENEDO DE LA VEGA',
 'REOCIN': 'REOCÍN',
 'REUS': 'REUS',
 'REVILLA DE COLLAZOS': 'REVILLA DE COLLAZOS',
 'REZMONDO': 'REZMONDO',
 'RIAÃ‘O': 'RIAÑO',
 'RINCONADA (LA)': 'LA RINCONADA',
 'RIONANSA': 'RIONANSA',
 'RIOTORTO': 'RIOTORTO',
 'RIVAS-VACIAMADRID': 'RIVAS-VACIAMADRID',
 'RIVERO': None,
 'ROBLEDO DE CORPES': 'ROBLEDO DE CORPES',
 'RODA DE ANDALUCIA (LA)': 'LA RODA DE ANDALUCÍA',
 'ROIZ': 'OIZ',
 'RONCAL': None,
 'RONDA': 'RONDA',
 'RONQUILLO (EL)': 'EL RONQUILLO',
 'ROPERUELOS DEL PARAMO': 'ROPERUELOS DEL PÁRAMO',
 'ROQUETAS DE MAR': 'ROQUETAS DE MAR',
 'ROSES': 'ROSES',
 'ROSSELL': 'ROSSELL',
 'ROTA': 'ROTA',
 'RUBAYO': None,
 'RUBI': 'RUBÍ',
 'RUENTE': 'RUENTE',
 'RUESGA': 'RUESGA',
 'RUILOBA': 'RUILOBA',
 'RUTE': 'RUTE',
 'S.SEBASTIAN DE LA GOMERA': 'SAN SEBASTIÁN DE LA GOMERA',
 'S/C DE LA PALMA': 'SANTA CRUZ DE LA PALMA',
 'S/C DE TENERIFE': 'SANTA CRUZ DE TENERIFE',
 'SA POBLA': 'SA POBLA',
 'SABADELL': 'SABADELL',
 'SABIÃ‘ANIGO': 'SABIÑÁNIGO',
 'SADA': 'SADA',
 'SADABA': 'SÁDABA',
 'SALAMANCA': 'SALAMANCA',
 'SALOBREÃ‘A': 'SALOBREÑA',
 'SALOU': 'SALOU',
 'SALT': 'SALT',
 'SAN AMARO': 'SAN AMARO',
 'SAN BARTOLOME': 'SAN BARTOLOMÉ',
 'SAN BARTOLOME DE TIRAJANA': 'SAN BARTOLOMÉ DE TIRAJANA',
 'SAN CRISTOBAL DE BOEDO': 'SAN CRISTÓBAL DE BOEDO',
 'SAN CRISTOBAL DE LA CUESTA': 'SAN CRISTÓBAL DE LA CUESTA',
 'SAN CRISTOBAL DE LA LAGUNA': 'SAN CRISTÓBAL DE LA LAGUNA',
 'SAN CRISTOBAL DE SEGOVIA': 'SAN CRISTÓBAL DE SEGOVIA',
 'SAN CRISTOVO DE CEA': 'SAN CRISTOVO DE CEA',
 'SAN FELICES DE BUELNA': 'SAN FELICES DE BUELNA',
 'SAN FERNANDO': 'SAN FERNANDO',
 'SAN FERNANDO DE HENARES': 'SAN FERNANDO DE HENARES',
 'SAN ILDEFONSO': None,
 'SAN ILDEFONSO O LA GRANJA': None,
 'SAN JAVIER': 'SAN JAVIER',
 'SAN JOSE': None,
 'SAN JUAN DE AZNALFARACHE': 'SAN JUAN DE AZNALFARACHE',
 'SAN LEONARDO DE YAGÃœE': 'SAN LEONARDO DE YAGÜE',
 'SAN MAMES DE CAMPOS': 'SAN MAMÉS DE CAMPOS',
 'SAN MIGUEL DE ABONA': 'SAN MIGUEL DE ABONA',
 'SAN MIGUEL DE LUENA': None,
 'SAN MIGUEL DE MERUELO': None,
 'SAN PEDRO DE BREÃ‘A ALTA': 'ARENAS DE SAN PEDRO',
 'SAN VICENTE DE ALCANTARA': 'SAN VICENTE DE ALCÁNTARA',
 'SAN VICENTE DE LA BARQUERA': 'SAN VICENTE DE LA BARQUERA',
 'SAN VICENTE DE TORANZO': None,
 'SANLUCAR DE BARRAMEDA': 'SANLÚCAR DE BARRAMEDA',
 'SANLUCAR LA MAYOR': 'SANLÚCAR LA MAYOR',
 'SANT ANDREU DE LA BARCA': 'SANT ANDREU DE LA BARCA',
 'SANT ANTONI DE PORTMANY': 'SANT ANTONI DE PORTMANY',
 'SANT BOI DE LLOBREGAT': 'SANT BOI DE LLOBREGAT',
 'SANT CARLES DE LA RAPITA': None,
 'SANT CUGAT DEL VALLES': 'SANT CUGAT DEL VALLÈS',
 'SANT FELIU DE GUIXOLS': 'SANT FELIU DE GUÍXOLS',
 'SANT FELIU DE LLOBREGAT': 'SANT FELIU DE LLOBREGAT',
 'SANT FELIU DE PALLEROLS': 'SANT FELIU DE PALLEROLS',
 'SANT JOAN DE LABRITJA': 'SANT JOAN DE LABRITJA',
 'SANT JOSEP DE SA TALAIA': 'SANT JOSEP DE SA TALAIA',
 'SANT JULIA DE VILATORTA': 'SANT JULIÀ DE VILATORTA',
 'SANT LLUIS': 'SANT LLUÍS',
 'SANT MARTI DE TOUS': 'SANT MARTÍ DE TOUS',
 'SANT MARTI SARROCA': 'SANT MARTÍ SARROCA',
 'SANT MATEU': 'SANT MATEU',
 'SANT PERE DE RIBES': 'SANT PERE DE RIBES',
 'SANTA COLOMA DE FARNERS': 'SANTA COLOMA DE FARNERS',
 'SANTA COLOMA DE GRAMENET': 'SANTA COLOMA DE GRAMENET',
 'SANTA CRUZ DE BEZANA': 'SANTA CRUZ DE BEZANA',
 'SANTA CRUZ DE BOEDO': 'SANTA CRUZ DE BOEDO',
 'SANTA CRUZ DE TENERIFE': 'SANTA CRUZ DE TENERIFE',
 'SANTA EUFEMIA': 'SANTA EUFEMIA',
 'SANTA EUGENIA DE BERGA': 'SANTA EUGÈNIA DE BERGA',
 'SANTA EULARIA DES RIU': 'SANTA EULÀRIA DES RIU',
 'SANTA GADEA DEL CID': 'SANTA GADEA DEL CID',
 'SANTA LUCIA DE TIRAJANA': 'SANTA LUCÍA DE TIRAJANA',
 'SANTA MARGALIDA': 'SANTA MARGALIDA',

In [23]:
manual_corrections = {
    'ADEJE CASCO': 'ADEJE',
    'AGÃœIMES': 'AGÜIMES',
    'AJO': 'BAREYO', 
    'ALICANTE/ALACANT': 'ALACANT/ALICANTE',
    'ALMAZORA': 'ALMASSORA',
    'ALQUERIAS DEL NIÃ‘O PERDIDO': 'LES ALQUERIES/ALQUERÍAS DEL NIÑO PERDIDO',
    'BARRIO DE BRICIA': 'ALFOZ DE BRICIA',
    'BENICASIM': 'BENICÀSSIM/BENICASIM',
    'BORRIANA/BURRIANA': 'BORRIANA/BURRIANA',
    'BURRIANA': 'BORRIANA/BURRIANA',
    'CABANAQUINTA/CABAÃ‘AQUINTA': 'ALLER', 
    'CASTELLON DE LA PLANA': 'CASTELLÓ DE LA PLANA/CASTELLÓN DE LA PLANA',
    'EJEA': 'EJEA DE LOS CABALLEROS',
    'EL GOLFO': 'YAIZA', 
    'ELCHE': 'ELX/ELCHE',
    'ELCHE/ELX': 'ELX/ELCHE',
    'ELEXALDE': 'GALDAKAO', 
    'JAVEA': 'XÀBIA/JÁVEA',
    'JAVEA/XABIA': 'XÀBIA/JÁVEA',
    'LA ALMUNIA': 'LA ALMUNIA DE DOÑA GODINA',
    'LA CONCHA': 'VILLAESCUSA', 
    'LA IGLESIA': 'RUILOBA', 
    'LA POLA': 'LENA', 
    'LAS PALMAS DE G.C.': 'LAS PALMAS DE GRAN CANARIA',
    'LLANSA': 'LLANÇÀ',
    'MATAMOROSA': 'CAMPOO DE ENMEDIO',
    'MIERES DEL CAMIN': 'MIERES',
    'MORON FRONTERA': 'MORÓN DE LA FRONTERA',
    'MURIEDAS': 'CAMARGO',
    'OSORNO': 'OSORNO LA MAYOR',
    'PALMA DE MALLORCA': 'PALMA', 
    'PAMPLONA': 'PAMPLONA/IRUÑA',
    'PEÃ‘ISCOLA': 'PENÍSCOLA/PEÑÍSCOLA',
    'POLLENÃ‡A': 'POLLENÇA',
    'POMALUENGO': 'CASTAÑEDA',
    'PUENTENANSA': 'RIONANSA',
    'RENEDO': 'PIÉLAGOS', 
    'RIVERO': 'SAN FELICES DE BUELNA',
    'RONCAL': 'RONCAL/ERRONKARI',
    'RUBAYO': 'MARINA DE CUDEYO',
    'SAN ILDEFONSO': 'REAL SITIO DE SAN ILDEFONSO',
    'SAN ILDEFONSO O LA GRANJA': 'REAL SITIO DE SAN ILDEFONSO',
    'SAN JOSE': 'NÍJAR', 
    'SAN MIGUEL DE LUENA': 'LUENA',
    'SAN MIGUEL DE MERUELO': 'MERUELO',
    'SAN VICENTE DE TORANZO': 'CORVERA DE TORANZO',
    'SANT CARLES DE LA RAPITA': 'LA RÀPITA', 
    'SETLA': 'ELS POBLETS', 
    'SIGÃœENZA': 'SIGÜENZA',
    'TAMA': 'CILLORIGO DE LIÉBANA', 
    'TARRIO': 'AMES', # Tarrio is ambiguous. It is a village not an official administrative municipio
    'TORRE BAJA': 'TORREBAJA',
    'TORRE ENDOMENECH': "LA TORRE D'EN DOMÉNEC",
    'UZTARROZ': 'UZTÁRROZ/UZTARROTZE',
    'VALDECILLA': 'MEDIO CUDEYO',
    'VEGUILLA': 'SOBA',
    'VILLAJOYOSA/LA VILA JOIOSA': 'LA VILA JOIOSA/VILLAJOYOSA',
    'VILLAYUSO': 'CIEZA'
}

In [24]:
final_corrections = matches | manual_corrections
final = pd.DataFrame.from_dict(final_corrections, orient='index').reset_index()
final.columns = ['DE_MUNICIP_org', 'DE_MUNICIP']
final

              DE_MUNICIP_org               DE_MUNICIP
0                  A CORUÃ‘A                 A CORUÑA
1         ABIA DE LAS TORRES       ABIA DE LAS TORRES
2                     ABRERA                   ABRERA
3                    ACEBEDO                  ACEBEDO
4                   ACEUCHAL                 ACEUCHAL
..                       ...                      ...
803                 YUNQUERA                 YUNQUERA
804                    ZAFRA                    ZAFRA
805                 ZARAGOZA                 ZARAGOZA
806  ZARZOSA DE RIO PISUERGA  ZARZOSA DE RÍO PISUERGA
807                    ZUERA                    ZUERA

[808 rows x 2 columns]

In [25]:
final_merged = final.merge(latlong_data, on='DE_MUNICIP', how='left')
final_merged

,DE_MUNICIP_org,DE_MUNICIP,PROVINCE,LONGITUDE,LATITUDE
0,A CORUÃ‘A,A CORUÑA,A Coruña,-8.395826,43.371495
1,ABIA DE LAS TORRES,ABIA DE LAS TORRES,Palencia,-4.421902,42.420220
2,ABRERA,ABRERA,Barcelona,1.901569,41.516398
3,ACEBEDO,ACEBEDO,León,-5.115871,43.040732
4,ACEUCHAL,ACEUCHAL,Badajoz,-6.487251,38.647755
...,...,...,...,...,...
812,YUNQUERA,YUNQUERA,Málaga,-4.917332,36.734203
813,ZAFRA,ZAFRA,Badajoz,-6.418559,38.426344
814,ZARAGOZA,ZARAGOZA,Zaragoza,-0.877318,41.656208
815,ZARZOSA DE RIO PISUERGA,ZARZOSA DE RÍO PISUERGA,Burgos,-4.267593,42.536190
816,ZUERA,ZUERA,Zaragoza,-0.787165,41.868393

In [26]:
final_merged.isna().sum()

DE_MUNICIP_org    0
DE_MUNICIP        0
PROVINCE          1
LONGITUDE         1
LATITUDE          1
dtype: int64

In [27]:
final_merged[final_merged['LATITUDE'].isna()]

    DE_MUNICIP_org           DE_MUNICIP PROVINCE  LONGITUDE  LATITUDE
734       UZTARROZ  UZTÁRROZ/UZTARROTZE      NaN        NaN       NaN

In [28]:
all_districts = latlong_data['DE_MUNICIP'].tolist()
process.extract('UZTARROZ', all_districts, limit=5, scorer=fuzz.token_sort_ratio)

[('URROZ', 76.92307692307692, 7147),
 ('MAZARAMBROZ', 63.1578947368421, 4383),
 ('BULARROS', 62.5, 1340),
 ('ZARAGOZA', 62.5, 8061),
 ('BARRO', 61.53846153846154, 939)]

Distinct Municipalities: Uztárroz (Uztarrotze) and Urroz are two completely different, separate towns located in the province of Navarre.

In [29]:
final_merged.loc[734, 'LATITUDE'] = 42.9194
final_merged.loc[734, 'LONGITUDE'] = -0.9567
final_merged.loc[734, 'PROVINCE'] = 'Navarre'

In [30]:
final_merged.isna().sum()

DE_MUNICIP_org    0
DE_MUNICIP        0
PROVINCE          0
LONGITUDE         0
LATITUDE          0
dtype: int64

In [31]:
final_merged[final_merged['DE_MUNICIP_org'].duplicated(keep=False)]

       DE_MUNICIP_org   DE_MUNICIP            PROVINCE  LONGITUDE   LATITUDE
131           CABANES      CABANES  Castelló/Castellón   0.045412  40.156104
132           CABANES      CABANES              Girona   2.977957  42.307504
199             CIEZA        CIEZA              Murcia  -1.427730  38.236594
200             CIEZA        CIEZA           Cantabria  -4.096722  43.221056
340         LA CONCHA  VILLAESCUSA              Zamora  -5.464099  41.206136
341         LA CONCHA  VILLAESCUSA           Cantabria  -3.856639  43.370333
434            MIERES       MIERES              Girona   2.640292  42.123296
435            MIERES       MIERES            Asturias  -5.772657  43.248794
436  MIERES DEL CAMIN       MIERES              Girona   2.640292  42.123296
437  MIERES DEL CAMIN       MIERES            Asturias  -5.772657  43.248794
581              SADA         SADA             Navarra  -1.397668  42.585825
582              SADA         SADA            A Coruña  -8.253590  43.351531
720           TORRENT      TORRENT   València/Valencia  -0.465982  39.436721
721           TORRENT      TORRENT              Girona   3.128197  41.951843
773       VILLAESCUSA  VILLAESCUSA              Zamora  -5.464099  41.206136
774       VILLAESCUSA  VILLAESCUSA           Cantabria  -3.856639  43.370333
800         VILLAYUSO        CIEZA              Murcia  -1.427730  38.236594
801         VILLAYUSO        CIEZA           Cantabria  -4.096722  43.221056

In [32]:
final_merged.to_csv(r'../BD_MUNICIPIOS-ENTIDADES/DE_MUNICIP_LAT_LONG.csv')